[general]
import = [
  "~/.config/alacritty/themes/solarized-light.toml"
]

[window]
decorations = "full"
opacity = 1.0

[window.padding]
x = 16
y = 16

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Off"

[scrolling]
history = 10000

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true, mods = "Command" }
binding = { key = "U", mods = "Command" }
regex = '(https?://|ftp://|file://|mailto:|ssh://|git://|gemini://|gopher://)[^\s"<>]*'
